server:
  port: ${SERVER_PORT:8443}
  ssl:
    enabled: true
    key-store: ${SSL_KEYSTORE:/app/ssl/keystore.p12}
    key-store-password: ${SSL_KEYSTORE_PASSWORD:changeit}
    key-store-type: PKCS12
    key-alias: tomcat

spring:
  application:
    name: genocide-service

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info

city-service:
  base-url: ${CITY_SERVICE_URL:https://localhost:8443/}